### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by CityzenAF** [rizwansoaib/rizwansoaib#4]
Hey man, I was going through your sentiment analysis of whatsapp chat project and found it quite fascinating.........I tried to implement the same project on my system but I had some issues..........so when the chats are exported and stored in .TXT format the file often contains things like x removed y or y left the group.........so how to filter out these things and get only the things required?

Thanks

**Comment by CityzenAF** [comment]
Hey man, I was going through your sentiment analysis of whatsapp chat project and found it quite fascinating.........I tried to implement the same project on my system but I had some issues..........so when the chats are exported and stored in .TXT format the file often contains things like x removed y or y left the group.........so how to filter out these things and get only the things required?

Thanks

**Comment by rizwansoaib** [comment]
Using regex match pattern

**Comment by bhaumik1111** [comment]
hello bro @CityzenAF i need help for to open whatsapp on cloud and use same script for app in flutter
